timezone: America/New_York

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      author: "Kevin Meeks"
      title: "A Language a Week"
